spring:
  application:
    name=booking


  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  data:
    redis:
      expiration: 15
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    liquibase: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR

booking:
  expiration: 15