spring:
  application:
    name=booking

  datasource:
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.sql

server:
  port: 8080

