--liquibase formatted sql

--changeset Max:1
CREATE SEQUENCE IF NOT EXISTS user_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE SEQUENCE IF NOT EXISTS booking_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE SEQUENCE IF NOT EXISTS events_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE SEQUENCE IF NOT EXISTS payments_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE SEQUENCE IF NOT EXISTS unit_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE SEQUENCE IF NOT EXISTS unit_properties_seq_id
  START WITH 1
  INCREMENT BY 50
  NO MINVALUE
  CACHE 50;

CREATE TYPE event_type AS ENUM('CREATE', 'UPDATE', 'DELETE');
CREATE TYPE accommodation_type AS ENUM('HOME', 'FLAT', 'APARTMENTS');
CREATE TYPE payment_status AS ENUM('NOT_PAID', 'PAID', 'CANCELED');